name: Build CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install .

      - run: pip install pyinstaller

      - run: pyinstaller --onefile -n compliance -m compliance_guard.cli.main

      - uses: actions/upload-artifact@v4
        with:
          name: compliance-${{ matrix.os }}
          path: dist/*